"""Table that shows the associated data with each flag."""

from randomizer.Enums.Kongs import Kongs
from randomizer.Enums.Types import Types

class FlagItemConversion:
    """Class to store information regarding the flag item converter."""

    def __init__(self, item_type, item_kong=None):
        """Initialize with given data."""
        self.item_type = item_type
        self.item_kong = item_kong

FlagTable = {
    1: FlagItemConversion(Types.Banana),
	2: FlagItemConversion(Types.Banana),
	3: FlagItemConversion(Types.Banana),
	4: FlagItemConversion(Types.Banana),
	5: FlagItemConversion(Types.Banana),
	8: FlagItemConversion(Types.Banana),
	9: FlagItemConversion(Types.Banana),
	10: FlagItemConversion(Types.Banana),
	11: FlagItemConversion(Types.Banana),
	12: FlagItemConversion(Types.Banana),
	18: FlagItemConversion(Types.Banana),
	19: FlagItemConversion(Types.Banana),
	20: FlagItemConversion(Types.Banana),
	21: FlagItemConversion(Types.Banana),
	22: FlagItemConversion(Types.Banana),
	23: FlagItemConversion(Types.Banana),
	24: FlagItemConversion(Types.Banana),
	25: FlagItemConversion(Types.Banana),
	26: FlagItemConversion(Types.Key),
	28: FlagItemConversion(Types.Banana),
	31: FlagItemConversion(Types.Banana),
	49: FlagItemConversion(Types.Banana),
	51: FlagItemConversion(Types.Banana),
	52: FlagItemConversion(Types.Banana),
	54: FlagItemConversion(Types.Banana),
	56: FlagItemConversion(Types.Banana),
	57: FlagItemConversion(Types.Banana),
	58: FlagItemConversion(Types.Banana),
	59: FlagItemConversion(Types.Banana),
	60: FlagItemConversion(Types.Banana),
	62: FlagItemConversion(Types.Banana),
	63: FlagItemConversion(Types.Banana),
	64: FlagItemConversion(Types.Banana),
	65: FlagItemConversion(Types.Banana),
	67: FlagItemConversion(Types.Banana),
	68: FlagItemConversion(Types.Banana),
	71: FlagItemConversion(Types.Banana),
	72: FlagItemConversion(Types.Banana),
	73: FlagItemConversion(Types.Banana),
	74: FlagItemConversion(Types.Key),
	75: FlagItemConversion(Types.Banana),
	77: FlagItemConversion(Types.Banana),
	112: FlagItemConversion(Types.Banana),
	113: FlagItemConversion(Types.Banana),
	114: FlagItemConversion(Types.Banana),
	115: FlagItemConversion(Types.Banana),
	116: FlagItemConversion(Types.Banana),
	118: FlagItemConversion(Types.Banana),
	121: FlagItemConversion(Types.Banana),
	122: FlagItemConversion(Types.Banana),
	123: FlagItemConversion(Types.Banana),
	124: FlagItemConversion(Types.Banana),
	125: FlagItemConversion(Types.Banana),
	126: FlagItemConversion(Types.Banana),
	127: FlagItemConversion(Types.Banana),
	128: FlagItemConversion(Types.Banana),
	130: FlagItemConversion(Types.Banana),
	132: FlagItemConversion(Types.Coin),
	134: FlagItemConversion(Types.Banana),
	135: FlagItemConversion(Types.Banana),
	136: FlagItemConversion(Types.Banana),
	137: FlagItemConversion(Types.Banana),
	138: FlagItemConversion(Types.Key),
	139: FlagItemConversion(Types.Banana),
	154: FlagItemConversion(Types.Banana),
	157: FlagItemConversion(Types.Banana),
	163: FlagItemConversion(Types.Banana),
	164: FlagItemConversion(Types.Banana),
	165: FlagItemConversion(Types.Banana),
	166: FlagItemConversion(Types.Banana),
	167: FlagItemConversion(Types.Banana),
	168: FlagItemConversion(Types.Key),
	182: FlagItemConversion(Types.Banana),
	183: FlagItemConversion(Types.Banana),
	184: FlagItemConversion(Types.Banana),
	191: FlagItemConversion(Types.Banana),
	192: FlagItemConversion(Types.Banana),
	193: FlagItemConversion(Types.Banana),
	197: FlagItemConversion(Types.Banana),
	198: FlagItemConversion(Types.Banana),
	199: FlagItemConversion(Types.Banana),
	200: FlagItemConversion(Types.Banana),
	201: FlagItemConversion(Types.Banana),
	202: FlagItemConversion(Types.Banana),
	204: FlagItemConversion(Types.Banana),
	205: FlagItemConversion(Types.Banana),
	209: FlagItemConversion(Types.Banana),
	211: FlagItemConversion(Types.Banana),
	214: FlagItemConversion(Types.Banana),
	215: FlagItemConversion(Types.Banana),
	216: FlagItemConversion(Types.Banana),
	217: FlagItemConversion(Types.Banana),
	219: FlagItemConversion(Types.Banana),
	221: FlagItemConversion(Types.Banana),
	224: FlagItemConversion(Types.Banana),
	225: FlagItemConversion(Types.Banana),
	226: FlagItemConversion(Types.Banana),
	227: FlagItemConversion(Types.Banana),
	228: FlagItemConversion(Types.Banana),
	235: FlagItemConversion(Types.Banana),
	236: FlagItemConversion(Types.Key),
	247: FlagItemConversion(Types.Banana),
	249: FlagItemConversion(Types.Banana),
	250: FlagItemConversion(Types.Banana),
	253: FlagItemConversion(Types.Banana),
	254: FlagItemConversion(Types.Banana),
	259: FlagItemConversion(Types.Banana),
	260: FlagItemConversion(Types.Banana),
	261: FlagItemConversion(Types.Banana),
	262: FlagItemConversion(Types.Banana),
	263: FlagItemConversion(Types.Banana),
	264: FlagItemConversion(Types.Banana),
	268: FlagItemConversion(Types.Banana),
	270: FlagItemConversion(Types.Banana),
	271: FlagItemConversion(Types.Banana),
	274: FlagItemConversion(Types.Banana),
	275: FlagItemConversion(Types.Banana),
	276: FlagItemConversion(Types.Banana),
	278: FlagItemConversion(Types.Banana),
	279: FlagItemConversion(Types.Banana),
	281: FlagItemConversion(Types.Banana),
	292: FlagItemConversion(Types.Key),
	293: FlagItemConversion(Types.Banana),
	294: FlagItemConversion(Types.Banana),
	295: FlagItemConversion(Types.Banana),
	297: FlagItemConversion(Types.Banana),
	298: FlagItemConversion(Types.Banana),
	301: FlagItemConversion(Types.Banana),
	305: FlagItemConversion(Types.Banana),
	306: FlagItemConversion(Types.Banana),
	308: FlagItemConversion(Types.Banana),
	309: FlagItemConversion(Types.Banana),
	310: FlagItemConversion(Types.Banana),
	311: FlagItemConversion(Types.Banana),
	313: FlagItemConversion(Types.Banana),
	314: FlagItemConversion(Types.Banana),
	315: FlagItemConversion(Types.Banana),
	316: FlagItemConversion(Types.Banana),
	317: FlagItemConversion(Types.Key),
	318: FlagItemConversion(Types.Banana),
	319: FlagItemConversion(Types.Banana),
	320: FlagItemConversion(Types.Banana),
	322: FlagItemConversion(Types.Banana),
	323: FlagItemConversion(Types.Banana),
	325: FlagItemConversion(Types.Banana),
	326: FlagItemConversion(Types.Banana),
	350: FlagItemConversion(Types.Banana),
	351: FlagItemConversion(Types.Banana),
	353: FlagItemConversion(Types.Banana),
	379: FlagItemConversion(Types.Coin),
	380: FlagItemConversion(Types.Key),
	381: FlagItemConversion(Types.Banana),
	398: FlagItemConversion(Types.Banana),
	402: FlagItemConversion(Types.Banana),
	403: FlagItemConversion(Types.Banana),
	404: FlagItemConversion(Types.Banana),
	406: FlagItemConversion(Types.Banana),
	410: FlagItemConversion(Types.Banana),
	411: FlagItemConversion(Types.Banana),
	415: FlagItemConversion(Types.Banana),
	416: FlagItemConversion(Types.Banana),
	419: FlagItemConversion(Types.Banana),
	420: FlagItemConversion(Types.Banana),
	421: FlagItemConversion(Types.Banana),
	422: FlagItemConversion(Types.Banana),
	423: FlagItemConversion(Types.Banana),
	424: FlagItemConversion(Types.Banana),
	425: FlagItemConversion(Types.Banana),
	428: FlagItemConversion(Types.Banana),
	429: FlagItemConversion(Types.Banana),
	431: FlagItemConversion(Types.Banana),
	469: FlagItemConversion(Types.Blueprint, Kongs.donkey),
	470: FlagItemConversion(Types.Blueprint, Kongs.diddy),
	471: FlagItemConversion(Types.Blueprint, Kongs.lanky),
	472: FlagItemConversion(Types.Blueprint, Kongs.tiny),
	473: FlagItemConversion(Types.Blueprint, Kongs.chunky),
	474: FlagItemConversion(Types.Blueprint, Kongs.donkey),
	475: FlagItemConversion(Types.Blueprint, Kongs.diddy),
	476: FlagItemConversion(Types.Blueprint, Kongs.lanky),
	477: FlagItemConversion(Types.Blueprint, Kongs.tiny),
	478: FlagItemConversion(Types.Blueprint, Kongs.chunky),
	479: FlagItemConversion(Types.Blueprint, Kongs.donkey),
	480: FlagItemConversion(Types.Blueprint, Kongs.diddy),
	481: FlagItemConversion(Types.Blueprint, Kongs.lanky),
	482: FlagItemConversion(Types.Blueprint, Kongs.tiny),
	483: FlagItemConversion(Types.Blueprint, Kongs.chunky),
	484: FlagItemConversion(Types.Blueprint, Kongs.donkey),
	485: FlagItemConversion(Types.Blueprint, Kongs.diddy),
	486: FlagItemConversion(Types.Blueprint, Kongs.lanky),
	487: FlagItemConversion(Types.Blueprint, Kongs.tiny),
	488: FlagItemConversion(Types.Blueprint, Kongs.chunky),
	489: FlagItemConversion(Types.Blueprint, Kongs.donkey),
	490: FlagItemConversion(Types.Blueprint, Kongs.diddy),
	491: FlagItemConversion(Types.Blueprint, Kongs.lanky),
	492: FlagItemConversion(Types.Blueprint, Kongs.tiny),
	493: FlagItemConversion(Types.Blueprint, Kongs.chunky),
	494: FlagItemConversion(Types.Blueprint, Kongs.donkey),
	495: FlagItemConversion(Types.Blueprint, Kongs.diddy),
	496: FlagItemConversion(Types.Blueprint, Kongs.lanky),
	497: FlagItemConversion(Types.Blueprint, Kongs.tiny),
	498: FlagItemConversion(Types.Blueprint, Kongs.chunky),
	499: FlagItemConversion(Types.Blueprint, Kongs.donkey),
	500: FlagItemConversion(Types.Blueprint, Kongs.diddy),
	501: FlagItemConversion(Types.Blueprint, Kongs.lanky),
	502: FlagItemConversion(Types.Blueprint, Kongs.tiny),
	503: FlagItemConversion(Types.Blueprint, Kongs.chunky),
	504: FlagItemConversion(Types.Blueprint, Kongs.donkey),
	505: FlagItemConversion(Types.Blueprint, Kongs.diddy),
	506: FlagItemConversion(Types.Blueprint, Kongs.lanky),
	507: FlagItemConversion(Types.Blueprint, Kongs.tiny),
	508: FlagItemConversion(Types.Blueprint, Kongs.chunky),
	549: FlagItemConversion(Types.Medal),
	550: FlagItemConversion(Types.Medal),
	551: FlagItemConversion(Types.Medal),
	552: FlagItemConversion(Types.Medal),
	553: FlagItemConversion(Types.Medal),
	554: FlagItemConversion(Types.Medal),
	555: FlagItemConversion(Types.Medal),
	556: FlagItemConversion(Types.Medal),
	557: FlagItemConversion(Types.Medal),
	558: FlagItemConversion(Types.Medal),
	559: FlagItemConversion(Types.Medal),
	560: FlagItemConversion(Types.Medal),
	561: FlagItemConversion(Types.Medal),
	562: FlagItemConversion(Types.Medal),
	563: FlagItemConversion(Types.Medal),
	564: FlagItemConversion(Types.Medal),
	565: FlagItemConversion(Types.Medal),
	566: FlagItemConversion(Types.Medal),
	567: FlagItemConversion(Types.Medal),
	568: FlagItemConversion(Types.Medal),
	569: FlagItemConversion(Types.Medal),
	570: FlagItemConversion(Types.Medal),
	571: FlagItemConversion(Types.Medal),
	572: FlagItemConversion(Types.Medal),
	573: FlagItemConversion(Types.Medal),
	574: FlagItemConversion(Types.Medal),
	575: FlagItemConversion(Types.Medal),
	576: FlagItemConversion(Types.Medal),
	577: FlagItemConversion(Types.Medal),
	578: FlagItemConversion(Types.Medal),
	579: FlagItemConversion(Types.Medal),
	580: FlagItemConversion(Types.Medal),
	581: FlagItemConversion(Types.Medal),
	582: FlagItemConversion(Types.Medal),
	583: FlagItemConversion(Types.Medal),
	584: FlagItemConversion(Types.Medal),
	585: FlagItemConversion(Types.Medal),
	586: FlagItemConversion(Types.Medal),
	587: FlagItemConversion(Types.Medal),
	588: FlagItemConversion(Types.Medal),
	589: FlagItemConversion(Types.Fairy),
	590: FlagItemConversion(Types.Fairy),
	591: FlagItemConversion(Types.Fairy),
	592: FlagItemConversion(Types.Fairy),
	593: FlagItemConversion(Types.Fairy),
	594: FlagItemConversion(Types.Fairy),
	595: FlagItemConversion(Types.Fairy),
	596: FlagItemConversion(Types.Fairy),
	597: FlagItemConversion(Types.Fairy),
	598: FlagItemConversion(Types.Fairy),
	599: FlagItemConversion(Types.Fairy),
	600: FlagItemConversion(Types.Fairy),
	601: FlagItemConversion(Types.Fairy),
	602: FlagItemConversion(Types.Fairy),
	603: FlagItemConversion(Types.Fairy),
	604: FlagItemConversion(Types.Fairy),
	605: FlagItemConversion(Types.Fairy),
	606: FlagItemConversion(Types.Fairy),
	607: FlagItemConversion(Types.Fairy),
	608: FlagItemConversion(Types.Fairy),
	609: FlagItemConversion(Types.Crown),
	610: FlagItemConversion(Types.Crown),
	611: FlagItemConversion(Types.Crown),
	612: FlagItemConversion(Types.Crown),
	613: FlagItemConversion(Types.Crown),
	614: FlagItemConversion(Types.Crown),
	615: FlagItemConversion(Types.Crown),
	616: FlagItemConversion(Types.Crown),
	617: FlagItemConversion(Types.Crown),
	618: FlagItemConversion(Types.Crown),
	385: FlagItemConversion(Types.Kong, Kongs.donkey),
	6: FlagItemConversion(Types.Kong, Kongs.donkey),
	70: FlagItemConversion(Types.Kong, Kongs.lanky),
	66: FlagItemConversion(Types.Kong, Kongs.tiny),
	117: FlagItemConversion(Types.Kong, Kongs.chunky),
	768: FlagItemConversion(Types.Bean),
	186: FlagItemConversion(Types.Pearl),
	187: FlagItemConversion(Types.Pearl),
	188: FlagItemConversion(Types.Pearl),
	189: FlagItemConversion(Types.Pearl),
	190: FlagItemConversion(Types.Pearl),
}
